on:
  push:
    branches:
      - main

jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    name: A job to automate contrib in readme
    steps:
      - uses: actions/checkout@v3
      - name: Contributors List
        uses: actions/contributors-list@v2
        with:
          header-markdown: true
          footer-markdown: true
          file: README.md
